"use client";
import { useState } from "react";
import { Nav } from "@/components/Nav";

type DemoResult={result:unknown;upstream:string;trace:{hop:number;id:string;retained:string[];discarded:string[]}[];receipt:Record<string,unknown>};
export default function Playground(){
 const [method,setMethod]=useState("eth_chainId"); const [address,setAddress]=useState("0x0000000000000000000000000000000000000000"); const [data,setData]=useState<DemoResult|null>(null); const [busy,setBusy]=useState(false);
 async function run(){setBusy(true);setData(null);const params=method==="eth_getBalance"?[address,"latest"]:[];const r=await fetch("/api/relay",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({method,params})});setData(await r.json());setBusy(false)}
 function download(){if(!data)return;const b=new Blob([JSON.stringify(data.receipt,null,2)],{type:"application/json"});const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download="veil-privacy-receipt.json";a.click();URL.revokeObjectURL(u)}
 return <><Nav/><main className="play"><span className="badge">Public tester mode</span><h1>See what disappears.</h1><p className="lede" style={{margin:0}}>Send a safe read-only Ethereum RPC request through the VEIL prototype. Inspect the transport trace, then export a privacy receipt.</p><div className="playgrid"><section className="card"><small>Request</small><div className="field"><label>RPC method</label><select value={method} onChange={e=>setMethod(e.target.value)}><option>eth_chainId</option><option>eth_blockNumber</option><option>eth_getBalance</option></select></div>{method==="eth_getBalance"&&<div className="field"><label>Ethereum address</label><input value={address} onChange={e=>setAddress(e.target.value)}/></div>}<button className="btn primary" onClick={run} disabled={busy}>{busy?"Routing…":"Route through VEIL"}</button><p className="warn">Prototype only. This demo does not claim production anonymity, does not implement a production ring signature, and only allows read-only RPC methods.</p></section><section className="card"><small>Privacy comparison</small><div className="trace" style={{marginTop:16}}><div className="hop"><b>Direct RPC</b><span>Origin and request arrive at the same provider.</span></div><div className="hop"><b>VEIL design goal</b><span>Separate origin context from the final Ethereum-facing request.</span></div></div></section></div>{data&&<div className="playgrid"><section className="card"><small>Route trace</small><div className="trace" style={{marginTop:16}}>{data.trace.map(h=><div className="hop" key={h.id}><b>{h.hop}. {h.id}</b><span>retain: {h.retained.join(", ")} · discard: {h.discarded.join(", ")}</span></div>)}</div></section><section className="card"><small>Privacy receipt</small><p className="receipt">{JSON.stringify(data.receipt,null,2)}</p><button className="btn" onClick={download}>Export receipt</button></section></div>}</main></>
}
