import { Nav } from "@/components/Nav";

export default function Home(){return <>
<Nav/><main className="shell">
<section className="hero"><div className="kicker"><span className="dot"/> Public testnet prototype</div><h1>Ethereum should not need your whole life.</h1><p className="lede">VEIL is a privacy transport layer for Ethereum. It minimizes metadata leakage between a user or agent and the infrastructure that carries an Ethereum request.</p><div className="cta"><a className="btn primary" href="/playground">Run the privacy demo</a><a className="btn" href="/docs">Read the threat model</a></div></section>
<div className="proofbar"><div className="stat"><b>3</b><span>relay hops in demo</span></div><div className="stat"><b>0</b><span>accounts required</span></div><div className="stat"><b>1</b><span>click to generate receipt</span></div><div className="stat"><b>OSS</b><span>designed as public infrastructure</span></div></div>
<section id="how" className="section"><h2>Hide what Ethereum never asked for.</h2><p className="top">VEIL separates request origin, authorization and execution into narrow interfaces so intermediaries receive less identifying context.</p><div className="grid3"><div className="card"><small>01 / Intent</small><h3>Create locally</h3><p>A wallet or agent describes the Ethereum operation locally. Sensitive context is not treated as application telemetry.</p></div><div className="card"><small>02 / Transport</small><h3>Route minimally</h3><p>The request is wrapped and relayed. Each hop is designed to know less than an ordinary direct RPC provider.</p></div><div className="card"><small>03 / Receipt</small><h3>Prove the path</h3><p>Generate a deterministic privacy receipt containing hashes, policy version and disclosure-safe transport metadata.</p></div></div></section>
<section className="section"><h2>A test you can understand.</h2><p className="top">No wallet is required. Use the playground to compare a direct RPC request with the VEIL path, inspect each hop and export the resulting receipt.</p><div className="terminal"><div className="terminal-head"><span>veil / transport trace</span><span className="badge">ready</span></div><pre>{`direct_rpc:   origin → provider → ethereum\nveil_route:   origin → relay-a → relay-b → relay-c → ethereum\n\nprovider sees: request payload\nprovider does not need: original IP + app session + operator identity\n\nprivacy_receipt: sha256(intent || policy || route)`}</pre></div></section>
</main><div className="shell"><footer className="footer"><span>VEIL — metadata-private Ethereum transport</span><span>Prototype · Not audited · Do not use for high-value transactions</span></footer></div></>}
